name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger only if changes are made in the backend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (for EB CLI)
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install EB CLI
      run: |
        pip install awsebcli --upgrade

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create a ZIP file for backend
      run: |
        cd backend
        zip -r ../backend.zip .  # Create a zip file of the backend directory

    - name: Initialize EB
      run: |
        eb init ${{ secrets.EB_APP_NAME }} --platform docker --region ${{ secrets.AWS_REGION }} --verbose

    - name: Deploy to EB
      run: |
        eb deploy ${{ secrets.EB_ENV_NAME }}
