name: Deploy-Backend-to-ElasticBeanstalk

on:
  push:
    branches: [ main ]
    paths:    [ 'backend/**' ]   # Only run when backend/ changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out code
    - uses: actions/checkout@v3

    # 2. Python for the EB CLI
    - uses: actions/setup-python@v4
      with: { python-version: '3.11' }

    # 3. Install EB CLI
    - run: pip install --upgrade awsebcli

    # 4. Configure AWS creds from repo secrets
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ secrets.AWS_REGION }}

    # 5. Deploy (all done **inside backend/**)
    - name: Init & deploy backend
      working-directory: backend
      run: |
       
        eb init ${{ secrets.EB_APP_NAME }} \
                --platform docker \
                --region   ${{ secrets.AWS_REGION }} \
                --verbose

      
    - name: Deploy to EB
      run: |
        eb deploy ${{ secrets.EB_ENV_NAME }}
